baseurl = "https://www.examplelab.com.ar/"
languageCode = "en-us"
theme = "simple"

[params]
  contentTypeName = "posts"
  defaultTheme = "light"
  showMenuItems = 4
  showReadingTime = false

[markup.goldmark.renderer]
  unsafe= true

[languages]
  [languages.en]
    title = "Examplelab"
    subtitle = "Mi blog"
    keywords = ""
    copyright = ""
    menuMore = "Mostrar más"
    writtenBy = "Creado por"
    readMore = "Leer más"
    readOtherPosts = "Leer otros artículos"
    newerPosts = "Artículos nuevos"
    olderPosts = "Artículos anteriores"
    minuteReadingTime = "tiempo de lectura"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "examplelab"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "articulos"
        name = "Artículos"
        url = "/posts/index.html"
      [[languages.en.menu.main]]
        identifier = "proyectos"
        name = "Mis proyectos"
        url = "/proyectos/index.html"
      [[languages.en.menu.main]]
        identifier = "links"
        name = "Links"
        url = "/links/index.html"

      [[languages.en.menu.main]]
        identifier = "acerca de"
        name = "Sobre mí"
        url = "/about/index.html"
